#!/usr/bin/env python3
"""Build assembled/habits.md and assembled/habits.json from habits/*.md.

Each habit file is frontmatter, then a `## Snippet` section (the text destined for a
system prompt) and a `## Why` section (rationale, for me, excluded from output).

No third-party dependencies on purpose — this has to run anywhere without a venv, so
the frontmatter parser handles only the scalar and inline-list forms actually used.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HABITS = ROOT / "habits"
OUT = ROOT / "assembled"

SCALARS = ("id", "title", "stance", "added", "status", "source")


def parse(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        sys.exit(f"{path.name}: missing frontmatter")
    _, fm, body = text.split("---\n", 2)

    meta = {}
    for line in fm.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, _, value = line.partition(":")
        key, value = key.strip(), value.strip()
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            meta[key] = [v.strip() for v in inner.split(",") if v.strip()]
        elif key == "order":
            meta[key] = int(value)
        else:
            meta[key] = value.strip('"').strip("'")

    for key in ("id", "title", "stance", "order"):
        if key not in meta:
            sys.exit(f"{path.name}: frontmatter missing '{key}'")
    if meta["id"] != path.stem:
        sys.exit(f"{path.name}: id '{meta['id']}' does not match filename")
    if meta["stance"] not in ("practice", "prohibition"):
        sys.exit(f"{path.name}: stance must be practice or prohibition")

    sections = {}
    for match in re.finditer(r"^## (.+?)\n(.*?)(?=^## |\Z)", body, re.S | re.M):
        sections[match.group(1).strip().lower()] = match.group(2).strip()
    if "snippet" not in sections:
        sys.exit(f"{path.name}: no '## Snippet' section")

    meta["snippet"] = sections["snippet"]
    meta["why"] = sections.get("why", "")
    return meta


def main():
    files = sorted(HABITS.glob("*.md"))
    if not files:
        sys.exit(f"no habit files found in {HABITS}")
    habits = sorted((parse(p) for p in files), key=lambda h: h["order"])

    ids = [h["id"] for h in habits]
    for habit in habits:
        for ref in habit.get("related", []):
            if ref not in ids:
                sys.exit(f"{habit['id']}: related habit '{ref}' does not exist")

    OUT.mkdir(exist_ok=True)

    md = [
        "# Habits",
        "",
        "<!-- Generated by scripts/assemble.py — edit habits/*.md, not this file. -->",
        "",
        "Standing habits, in force before the task is known.",
        "",
    ]
    for habit in habits:
        md += [f"## {habit['title']}", "", habit["snippet"], ""]
    (OUT / "habits.md").write_text("\n".join(md), encoding="utf-8")

    payload = {
        "generated_by": "scripts/assemble.py",
        "count": len(habits),
        "habits": [
            {k: h[k] for k in ("id", "title", "stance", "order", "snippet") if k in h}
            | {k: h[k] for k in ("added", "status", "source", "related") if k in h}
            for h in habits
        ],
    }
    (OUT / "habits.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    print(f"{len(habits)} habits -> assembled/habits.md, assembled/habits.json")


if __name__ == "__main__":
    main()
